[package]
name = "tuun"
version = "0.3.0" # scrobbling, rich presence, and arturl
edition = "2021"

[dependencies]
chrono = "0.4.38"
discord-rich-presence = "0.2.5"
lazy_static = "1.5.0"
rustfm-scrobble = "1.1.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
ureq = "2.10.1"
