[package]
name = "tuun"
version = "2.0.0" # significant reorganization, misc improvements, better ux
edition = "2024"

[features]
default = []
debug = []

[dependencies]
anyhow = "1.0.96"
discord-rich-presence = "0.2.5"
once_cell = "1.20.3"
rustfm-scrobble = "1.1.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"
winit = "0.30.9"
