[package]
name = "tuun"
version = "0.5.6" # updated to ureq 3
edition = "2024"

[dependencies]
chrono = "0.4.39"
dirs = "5.0.1"
discord-rich-presence = "0.2.5"
lazy_static = "1.5.0"
rustfm-scrobble = "1.1.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
toml = "0.8.19"
ureq = { version = "3.0.5", features = ["json"] }
