[package]
name = "tuun"
version = "2.1.2" # tweaked log file destination, improved default value logic (hopefully)
edition = "2024"

[dependencies]
anyhow = "1.0.96"
discord-rich-presence = "0.2.5"
once_cell = "1.20.3"
rustfm-scrobble = "1.1.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
winit = "0.30.9"
