# Template config
# Defaults are given here. If a field is not specified, its default is used.

[lastfm]
used = false
apikey = "<your lastfm api key>"
secret = "<your lastfm secret>"
user = "<your lastfm username>"
password = "<your lastfm password>"
# percent of the song that must play before scrobbles
# should be a whole number between 10 and 100
scrobble_percent = 44

[discord]
used = true
# you can override my client ID with yours if you like
client_id = "1272345557276295310"
# an image url
fallback_art = "https://files.catbox.moe/rdwkcx.png"
# pick a custom image for the small asset (resolves #7)
small_image = "https://cdn.discordapp.com/avatars/1073248324024537208/7be772e2bc1afd0ddf0165b4ccfe3eb8.webp"
small_text = "hiii"
# timeout in milliseconds for connecting to discord's ipc socket
timeout = 100

# hex code
# 6-char and 3-char are supported
# starting # is optional
[color]
primary = "#f35f7a"
secondary = "3b4e84"
tertiary = "#e5e5e5"

[general]
shuffle = true
# `$HOME` and `~` are the only path expansions allowed
music_dir = "~/Music"
# if playlist is not specified, /tmp/tuun/all.tpl is used
# a tpl file is just a plain-text new-line-delimited list of absolute paths
playlist = "~/Music/Playlists/new.tpl"
# how many songs the /tmp/tuun/recent.tpl should consist of
recent_length = 200
# milliseconds to wait when polling mpv's socket on launch
mpv_socket_poll_timeout = 96
